import time
def fight(character):

    if character == "Elsa":
        print("")
        print("You try to lift up the chair and throw it, but you lack the strength to do any damage.")
        print("The attacker dives for you and stabs you with the knife. ")
        print("You were a threat as soon as you tried to fight back.")
        print("")
        print("You are dead")
        print("")
        print("Your game has ended.")
        print("")
        print("...but all is not lost. You can try again. Good luck in your next life.")
        print("")
        quit()

    if character == "Fish":
        print("")
        print("As you lift up the chair you here a crack and remember that you have a weak back.")
        print("The pain continues untill you can no longer stand.")
        print("As you vision goes black you see the attacker coming towards you.")
        print("... then nothingness.")
        print("")
        print("You have died.")
        print("")
        print("Instead of dieing in shame you can rise again.")
        print("Do you wish to die a hero instead?")
        print("")
        quit()

    if character == "Lily":
        print("")
        print("You throw the chair at the approaching person as hard as you can.")
        print("The chair strikes them in the head, causing them to pass out, before they managed to hurt anyone.")
        print("Breathing heavily you look around at your classmates. They are looking at you in admiring shock.")
        print("You are now the silently elected leader of the class.")
        print("")
        print("Now it is your job to figure out what to do next.")
        print("")
        print("You can either steal the attackers stuff or call authorities.")
        print("")
        print("1. Steal.")
        print("2. Call.")
        print("")

        while True:
            userAnswerthree = input()
            if userAnswerthree == "1" or userAnswerthree.lower() == "steal":
                print("")
                print("You dig through the attackers pockets and find a variety of weapons not just the knife.")
                print("You distribute the wepons to all your classmates, exept Griffen.")
                print("You and your classmates discuss and deside to train with the weapons and become a gang for justace and fight back against other attackers.")
                print("Your lives will be changed forever.")
                print("")
                print("If you do not like this ending, feel free to try again.")
                print("")
                quit()
            elif userAnswerthree == "2" or userAnswerthree.lower() == "call":
                print("")
                print("You call the authorities and they arrive shortly.")
                print("They thank you, and request that you continue on with your day as usual.")
                print("Your teacher arrives and administers the math test. You realize you don't understand anything on it.")
                print("")
                print("Despite the heroics of the day you still fail your math test. Things really are just like they were before.")
                print("")
                print("If failing math tests are not your ideal happy ending then try again. Good luck!")
                print("")
                quit()
            else :
                print("")
                print("That was not one of the options. ")
                print("Your options are...")
                print("")
                print("1. Steal.")
                print("2. Call.")
                print("")

def flight(character):
    if character == "Lily":
        print("")
        print("You wildly stand and run to the other side of the classroom trying to get out.")
        print("Unfortunately in the panic you trip over a backpack and fall on your face.")
        print("Your nose hurts like fire. Blood and tears run down your face. The fear and pain causes you to black out.")
        print("")
        print("Hours later you wake to find yourself in a hospital bed with a permanently twisted nose and a broken arm.")
        print("Could have been worse.")
        print("")
        print("Want to start your life over again without permanent injuries?")
        print("")
        print("This could be a begining. Try again if it suits you.")
        print("")
        quit()

    if character == "Elsa":
        print("")
        print("You hurridly stand up and bolt for the window, your heart beating wildly. Luckly you are a quick runner.")
        print("You make it to the window and shakily unlatch it.")
        print("Hopping out, you quickly flatten yourself to the wall as a couple of people follow you out the window.")
        print("")
        print("You can wait outside the window to help others escaping, or you can keep running home.")
        print("")
        print("1. Stay.")
        print("2. Run.")
        print("")
        
        while True:
            userAnswerfour = input()
            if userAnswerfour == "1" or userAnswerfour.lower() == "stay":
                print("")
                print("You stay near the window and quiety listen to what is happening inside as you help your peers escape.")
                print("Before escaping yourself you overhear a phone call from the attacker.")
                print("Once you make it to the evacuation spot you are questioned by police and you share what you heard.")
                print("")
                print("Later in the week you get an Email from secret services asking to recruit you after you get out of school.")
                print("You are now a secret agent.")
                print("Your career is now assured.")
                print("")
                print("Wish to try again?")
                print("Go right ahead.")
                print("")
                quit()
            elif userAnswerfour == "2" or userAnswerfour.lower() == "run":
                print("")
                print("You run as fast as you can, not looking back, even as screams are heard behind you.")
                print("You run until you finaly make it home.")
                print("You have made it out safely.")
                print("")
                print("A couple hours later you get an angry phone call from the school complaining that you did not meet up at the evacuation spot.")
                print("You explain that you were not going to risk your life for a math test, but no luck.")
                print("You have lunch detention.")
                print("")
                print("Don't like this ending? Keep playing!")
                print("")
                quit()
            else:
                print("")
                print("That was not one of the opptions. ")
                print("Your options are...")
                print("")
                print("1. Stay.")
                print("2. Run.")
                print("")
                
    if character == "Fish":
        print("")
        print("You try to get up but your desk is right next to the door.")
        print("Your movement alerts the attacker and they scream as they charge right at you.")
        print("Your chair tips backwards and you fall, crying out in fright.")
        print("The attacker jumps on top of your chest and stabs you repeatedly.")
        print("")
        print("unsurprisingly, after that you die.")
        print("")
        print("You should try again. That was just sad.")
        print("")
        quit()

def freeze(character):
    if character == "Lily":
        print("")
        print("Terror overcomes you and you freeze in place.")
        print("You watch as across the classroom the attacker killes your classmates.")
        print("Just when you think you finaly have control over your body again, you look up and find the attacker looming over you.")
        print("As you stare into their cruel eyes you do one last act of defiance for all your fallen friends and spit on their shoes.")
        print("The attackers eyes widen then narrow, and that is the last thing you see as red takes over your mind and body.")
        print("")
        print("You have definitely died.")
        print("")
        print("Good job dying like a rebel while being frozen in fear. Try again and survive like a rebel too!")
        print("")
        quit()

    if character == "Elsa":
        print("")
        print("As the chaos begings you are jostled from all sides.")
        print("Though your brain is screaming at you to move or do something all you can do is stand there.")
        print("Eventually after the blood bath, the attacker scans the room one last time before leaving you still standing there in puddles of blood.")
        print("")
        print("Eventually you are found by rescue survices and sent to the hospital.")
        print("You will never know why you were spared instead of your many classmates, just that you were.")
        print("")
        print("Is this really a satisfactory ending for you?")
        print("Try your luck on another go.")
        print("")
        quit()

    if character == "Fish":  
        print("")
        print("You stare at the attacker and the attacker stares right back.")
        print("A shudder shakes your entire body and terror glues your feet to the ground and your hands to your desk.")
        print("You are not even sure you are breathing.")
        print("Your vision goes blurry and your heart is pounding in your ears.")
        print("The attacker wades bloodily through the room towards you and grabs your limp hand.")
        print("They ask in a deep gravelly voise, 'Why aren't you afraid of me?'")
        print("Fearful tears prick your eyes but nevertheless you try to play along and you tell them that 'love of math and your longing to become friends gives you strength.'")
        print("The attacker drops your hand and begins to explain their life story.")  
        print("You listen to how they were abandend by their father and were then bullied for it constantly at school.")
        print("After a bit, they agree to join your math class.")
        print("")
        print("Half way through your math test you get nudged roughly by the attacker.")
        print("They ask you for your test answers.")
        print("You can either give them the answers or refuse to cheat.")
        print("")
        print("1. Give.")
        print("2. Refuse.")
        print("")

        while True:
            userAnswerfive = input()
            if userAnswerfive == "1" or userAnswerfive.lower() == "give":
                print("")
                print("You shakily hand over your test to the attacker when you thought the teacher was looking away.")
                print("The attacker grins at you and say that you and them are now best friends, and he will always protect you.")
                print("You decide to try and change them for good, now that you both are friends.")
                print("")
                print("Three months later you take your new best friend out to dinner, without them killing anyone.")
                print("This is progress!")
                print("")
                print("This is one happy ending, but how many can you find?")
                print("Try again to find out.")
                print("")
                quit()
            elif userAnswerfive == "2" or userAnswerfive.lower() == "refuse":
                print("")
                print("You glare at them and say that you will not cheat.")
                print("You watch as their face slowly crumples into anger and feel a sinking feeling in your gut.")
                print("You hastily apologize but it is not enough.")
                print("They stab you in the back with the knife and as you lie on the ground you see the attacker, your would-be friend staring back at you.")
                print("As your vision starts to fade you see the tears running down the attackers face and the sadness in their eyes.")
                print("The last thing you see is the attacker slowly turn around, head bowed and walk away.")
                print("")
                print("You died.")
                print("")
                print("Not only have they died you have broken the attackers heart. I wonder if they will ever be able to trust again.")
                print("")
                print("Try again and attempt to find a better ending for everyone.")
                print("")
                quit()
            else:
                print("")
                print("That was not one of the options. ")
                print("Your options are...")
                print("")
                print("1. Give.")
                print("2. Refuse.")
                print("")

def join(character):
    if character == "Lily":
            print("")
            print("Still trying to understand what is going on you keep questioning your friends as you run.")
            print("Suddenly you realize that you and your friends have been separated from the group.")
            print("You are your friends keep running until you reach the exit.")
            print("In front of you is a person covered in blood, bodies surrounding them, holdning a knife and grinning crazily at you.")
            print("")
            print("Safe to say you did not make it out alive.")
            print("")
            print("Want to try again?")
            print("Piece of advice for you. Do not get distracted when running from a killer.")
            print("")
            quit()

    if character == "Elsa":
        print("")
        print("You turn to run with the rest of the class, when you hear a thump in front of you.")
        print("You slow down and try to peer over your classmate's heads when you hear someone shout 'The attacker is coming!'")
        print("This news causes a panic to try and go the otherway and you fall in the chaos.")
        print("From under the feet of screaming students you reach the conclusion that you are doomed.")
        print("You go limp and let the heavy feet of others knock you out.")
        print("")
        print("You wake up at home with a nasty headache and bruses on every part of you.")
        print("You must not have been found, and even if you were, you looked dead enough not to be bothered with.")
        print("")
        print("Want to make it out healthy?")
        print("Next try is your game.")
        print("")
        quit()

    if character == "Fish":
        print("")
        print("You decide to join your franticly running classmates.")
        print("You run in the middle of the group and try to keep up with the rest of the class.")
        print("That is, until someone at the front yells 'The attacker is coming!'")
        print("You look ip and see a peron holding a knife, and covered in blood ruuning towards your group with murder in their eyes.")
        print("The group panics and starts to run in all directions.")
        print("")
        print("You can continue with the group, or stuff yourself into a nearby locker.")
        print("")
        print("1. Group.")
        print("2. Locker.")
        print("")

        while True:
            FishUltimateChose = input()
            if FishUltimateChose == "1" or FishUltimateChose.lower() == "group":
                print("")
                print("You run as fast as you can with the group in the general opposite direction of the attacker.")
                print("Eventually your legs tire, sweat runs down your face, your breath comes in ragged gasps, and your back screams almost as loud as the voices behind you.")
                print("One of your classmates run into you, and flailing at the unexpecting contact, they push you away.")
                print("You fall and hit your head against a wall and another classmate steps on you, causing your ankle to twist at an odd angle.")
                print("Trying to continue causes you to fall again and scream in pain.")
                print("With no other options and the hall now empty you try to crawl after your classmates.")
                print("Despite your efforts, you can not go very far.")
                print("The attacker finds you crawling, and kicks you into the wall before stabbing you in the side.")
                print("")
                print("Somehow you survive, but you lose a lot of blood and can't walk on your leg after the incident.")
                print("")
                print("You have a long impossible road to recovery ahead of you.")
                print("If you would like to skip the recovery prosses, try again.")
                print("")
                quit()
            elif FishUltimateChose == "2" or FishUltimateChose.lower() == "locker":
                print("")
                print("In the confusion, you run to the nearest locker and remove its contents.")
                print("You stand as straight as you can, and step inside the locker.")
                print("You shut the door and watch out the slits as your friends and classmates bleed out and die.")
                print("When the attcker finished with their massacre, they run after the escapees.")
                print("Your legs lock up and you start to shake.")
                print("You eventually step outside the locker and stare at the body directly in front of you.")
                print("You realize she is a quiet girl you know in class, and also despite the blood surounding her, she is still breathing.")
                print("On closer examination, she wasn't stabed, just knocked out.")
                print("You grab her unconscious body and drag her to the exit that was farthest from the attackers chase.")
                print("You make it outside and hide in a bush where you find a couple of other students who say they escaped out the classroom window.")
                print("")
                print("You and those you found make it home alive.")
                print("Can you save any more of your killed classmates?")
                print("Try it.")
                print("")
                quit()
            else:
                print("")
                print("That was not one of the options. ")
                print("Your options are...")
                print("")
                print("1. Group.")
                print("2. Locker.")
                print("")

def lead(character):
    if character == "Lily":
        print("")
        print("You think everyone would have a better chance of escaping the school if you lead.")
        print("You speed up and find the person at the front of the group.")
        print("Overtaking them you make a sharp turn in order to lead the group to an emergency exit that will sound alarms if opened.")
        print("You hope the attacker will not know about it.")
        print("After the turn, the class starts to slow and sounds of exhaustion and confusion come from them.")
        print("A couple of students come over and ask why we are taking a different route.")
        print("Time is at the essence and none of you have time for this.")
        print("")
        print("You can reassure them by saying, 'Trust me for real,' or you can tell them to 'Shut up and follow me.'")
        print("")
        print("1. Trust.")
        print("2. Shut up.")
        print("")
        
        while True:
            TalkUserAnswer = input()
            if TalkUserAnswer == "1" or TalkUserAnswer.lower() == "trust":
                print("")
                print("You tell them to 'Trust me for real.'")
                print("In their fear and confusion they seem to really want that, and you have been friends for years.")
                print("They agreeably help you gather up the rest of the students and you all start to run again.")
                print("You make it to the emergency exit and open the door.")
                print("The alarm goes off, and a feeling of relif fills the scared students.")
                print("You have made it out!")
                print("")
                print("Your classmates now treat you like a savior and you even earn a school reward during graduation.")
                print("Whats better then that?")
                print("Why don't you find out?")
                print("")
                quit()
            elif TalkUserAnswer == "2" or TalkUserAnswer.lower() == "shut up":
                print("")
                print("You tell them to 'Shut up and follow me.'")
                print("You don't normally talk like this, and the roughness seems to rattle your scared, emotionaly weak classmates.")
                print("They say nothing, but as you run you notice that groups of them are breaking off and runing down different halls.")
                print("You don't know what to do, but keep running with who is left.")
                print("At the door you find that you are only one of seven students that stayed in the group.")
                print("Even though you make it out safely you can't stop thinking about the students who left especially after you learn that only sixteen students survived out of the fifty in the group initially.")
                print("You are now a school hero, but you feel like a coward.")
                print("")
                print("Is this how you want to be remembered?")
                print("If it isn't, keep trying.")
                print("")
                quit()
            else:
                print("")
                print("That was not one of the options. ")
                print("Your options are to say...")
                print("")
                print("1. Trust.")
                print("2. Shut up.")
                print("")

    if character == "Fish":
        print("")
        print("You don't feel like a leader but you also feel like the only one left who can do it.")
        print("As you try to yell over the crowd you realize you are not alone in this feeling, because everyone is talking at once.")
        print("You try to be heard but no one is in the mood to listen.")
        print("In your frustration you start screaming.")
        print("The people around you panic at the sudden high pitched noise, and also start to scream.")
        print("Before you can calm everyone again, a person covered in blood appears around a bend in the hall.")
        print("Feeling responsible for being found you confront the stranger.")
        print("As you get closer you see the gleeming blood soked knife they are holding in their left hand.")
        print("Shuddering you try to remain standing but your legs can no longer hold you.")
        print("'What do you want?' you ask in a quivering squeak from the floor.")
        print("The attacker looks down at you before growling in a deep voise, 'Nothing anymore.'")
        print("Dread fills you compleatly.")
        print("")
        print("You have died! Congrats!")
        print("")
        print("Maybe try surviving next time? Good luck!")
        print("")
        quit()

    if character == "Elsa":
        print("")
        print("You don't trust any of your panicking classmates to lead.")
        print("You take a deep breath and start trying to find a familiar face.")
        print("Once you find someone you recognize, you run over and ask them to get everyone's attention.")
        print("Your friend is in too much shock and does not say anything.")
        print("You try to shake them out of it, but they are not responding.")
        print("You find another acquaintance named Griffen, but no luck with them either.")
        print("Giving up, you drag the closest people with you and start running down the hall.")
        print("You hide the people you grabbed under tables in the cafeteria.")
        print("You then go back to the group and grap a couple more, this time shoving them into empty lockers.")
        print("On your seventh try, you find the group compleatly slaughtered with a person standing in the middle if it all, smiling.")
        print("Fear engulfs you, as the attacker slowly walks closer and raises the knife.")
        print("You try to run but that just causes you to slip in blood and fall.")
        print("The knife finds its prey.")
        print("")
        print("You die, but you saved seventeen people, and some others that saw what you were doing and hide too.")
        print("You may die a hero, but don't you want to live as one too?")
        print("")
        print("Give it a try.")
        print("")
        quit()
    
def solo(character):

    if character == "Lily":
        print("")
        print("You pound through the halls, panting heavily.")
        print("Being alone in the school with a killer was terrifying.")
        print("Rounding a bend, you run into another student.")
        print("Screaming you run blindly the other way, until you turn another bend and find a bloody body.")
        print("Screaming again you turn... into the cold hand of a stranger.")
        print("")
        print("The last thing you see is their eyes staring into yours, as the knife burries itself into your throat.")
        print("")
        print("Brutal. Try again, but quieter this time.")
        print("")
        quit()

    if character == "Fish":
        print("")
        print("Spliting from the group you try for the kitchen and the delivery door inside.")
        print("As you run, your breath is shallow and your sight starts to narrow to the laces on your shoes.")
        print("You miss the first step, and stumble-fall down some stairs.")
        print("You scream as pain and a snap in your ankle causes your vision to turn red.")
        print("From the ground you see one of your friends, Griffen, hiding under a nearby table.")
        print("Their scared eyes meet yours and they beckon for you to hide with them.")
        print("You try and fail. They scramble over, and suport you as the two of you strumble to a hiding place.")
        print("Before you reach it panic grips you as seemingly in slow motion, a knife starts to protrude from Griffens forehead.")
        print("Blood is all you see as the knife turns on you.")
        print("")
        print("You and griffen have died.")
        print("")
        print("Way to drag your friend into it. Wow. Next time don't do that. That means its time to try again.")
        print("")
        quit()

    if character == "Elsa":
        print("")
        print("The others will just slow you down.")
        print("Running down the halls you try to think of a viable escape route.")
        print("You consided so many diffrent directions, you seem to have gotten turned around.")
        print("You are now in the middle school wing, and have no idea where you are.")
        print("")
        print("You can either continue trying to escape or hide in the girls bathroom.")
        print("")
        print("1. Continue.")
        print("2. Hide.")
        print("")
        
        while True:
            elsaSoloRun = input()
            if elsaSoloRun == "1" or elsaSoloRun.lower() == "continue":
                print("")
                print("You run, not even sure of which side of the school you are on.")
                print("You finaly realize where you are, when you stand in a puddle of your own blood mixed with at least five others in the cafeteria.")
                print("")
                print("Have you ever heard of staying put when lost? That lesson would have served you well.")
                print("")
                print("Panic is not the answer. Try again and use this knollage.")
                print("")
                quit()
            elif elsaSoloRun == "2" or elsaSoloRun.lower() == "hide":
                print("")
                print("You run into the girl's middle school bathroom and notice a group of huddling twelve-year-olds.")
                print("Sighing you show them how to sit on the toilets and lock the stall doors so it looks like no one is there.")
                print("Two hours later a rescue team enters the bathroom and the the terrified twelve-year-olds revealed themselfs.")
                print("")
                print("You have made it home from school alive! With a new group of admirers! errific!")
                print("")
                print("If you dislike middle schoolers, play again with diffrent choises. Good luck!")
                print("")
                quit()
            else:
                print("")
                print("That was not one of the options. ")
                print("Your options are...")
                print("")
                print("1. Continue.")
                print("2. Hide.")
                print("")

# A very dangourous day at school

character = 0
print("")
print("Welcome to school!")
print("")
print("You go to the School of High Level Math or the students call it SHELM, located in the North West area of the world.")
print("The school belives in math, lockers with no locks, and no late penlties.")
print("")
print("The progress you make relies on your character and the results of your choices.")
print("")
print("Choose your character.")
print("")
print("1. Lily: Lily is charasmatic and strong yet quite clumsy. Lily is reckless and can play soccer. She also hates math.")
print("2. Fish: Fish has an interesting point of view and can make friends with anyone. Fish is chaotic, and has a weak back.")
print("3. Elsa: Elsa is calm, collected, and smart, but also very quiet. She is quick on her feet, but is sorta weak.")
print("")

# Character Choice
firstuserAnswer = input()
if firstuserAnswer == "1" or firstuserAnswer.lower() == "lily":
    print("")
    print("You are now Lily. Woo hoo!")
    character = "Lily"
    print("")  
elif firstuserAnswer == "2" or firstuserAnswer.lower() == "fish":
    print("")
    print("You are now Fish. You chose... wisly.")
    character = "Fish"
    print("")
elif firstuserAnswer == "3" or firstuserAnswer.lower() == "elsa":
    print("")
    print("You are now Elsa. Yay!")
    character = "Elsa"
    print("")
else: 
    print("")
    print("That is not one of the characters. you will now recieve a random character.")
    print("")
    import random
    character = random.choice(["Lily", "Fish", "Elsa"])
    print("You are now " + character + ". Good luck!")
    print("")

while True:
    # Choice one
    print("")
    print("You are midway through spring trimester, and it is another day at school like any other.")
    print("On your way to class you remember that you have a math test today.")
    print("You get a chill and have a bad feeling about something.")
    print("")
    print("You can either go to class and take your math test or skip class and miss it.")
    print("")
    print("What do you want to do?")
    print("")
    print("1. Go.")
    print("2. Skip.")
    print("")

    # Go to class.
    userAnswer = input()
    if userAnswer == "1" or userAnswer.lower() == "go":
        print("")
        print("You decide to go to class. You walk into the classroom and sit down, ready to take the test.")
        print("The bell rings and almost immediately a stranger slowly enters the room. You can see they are holding a long jagged knife.")
        print("The fear is real.")
        print("")
        print("You have three options to try and make it out alive.")
        print("You can fight back by throwing the closest chair you can find, flee out the first floor window opposite the door,")
        print("or you can freeze and stand there in fear.")
        print("")
        print("What do you do?")
        print("")
        print("1. Freeze.")
        print("2. Flight.")
        print("3. Fight.")
        print("")
        secondAnswer = input()

        # Fight
        if secondAnswer == "3" or secondAnswer.lower() == "fight":
            fight(character)

        # Flight
        if secondAnswer == "2" or secondAnswer.lower() == "flight":
            flight(character)

        # Freeze
        if secondAnswer == "1" or secondAnswer.lower() == "freeze":
            freeze(character)


    # Skip class
    elif userAnswer == "2" or userAnswer.lower() == "skip":
        print("")
        print("You decide to keep walking down the hall, straight past your math classroom.")
        print("You feel a little guilty as you walk to a quieter part of the school, heading towards the storage room, When the bell for first period rings.")
        print("Suddenly, you hear footsteps and yelling down the hall. Like, a lot of them. Coming towards you.")
        print("You back up to get out of the away of the people running your way, pressing yourself agenst the wall.")
        print("You realize the people running are your classmates.")
        print("Not sure what to do, you grab on to one of your friends and ask them 'what's up.'")
        print("They tell you about a stranger with a knife in the classroom.")
        print("")
        print("You come up with four options of what to do next.")
        print("You can Join the group of escaping students, lead the pack, escape solo, or go to class to see things for yourself.")
        print("")
        print("1. Join.")
        print("2. Lead.")
        print("3. Solo.")
        print("4. Class.")
        print("")

        skipUserAnswerOne = input()
        if skipUserAnswerOne == "1" or skipUserAnswerOne.lower() == "join":
            join(character)

        if skipUserAnswerOne == "2" or skipUserAnswerOne.lower() == "lead":
            lead(character)

        if skipUserAnswerOne == "3" or skipUserAnswerOne.lower() == "solo":
            solo(character)

        if skipUserAnswerOne == "4" or skipUserAnswerOne.lower() == "class":
            print("")
            print("You make your way to your classroom despite the warnings from your classmates.")
            print("You are sure they must be playing a practical joke on you.")
            print("When you arrive you find blood seeping from the door.")
            print("Despite that you open the door and yawn to show how at ease you are.")
            print("On the other side of the door lays bodies and more blood and a person standing among it all.")
            print("This is real.")
            print("The person walks towards you and flicks their knife to remove the blood.")
            print("They run toward you and sink the knife into your left sholder then your right.")
            print("Your thigh is next.")
            print("You are dropped on the ground and bleed out.")
            print("")
            print("You have died.")
            print("")
            print("Try again, just this time don't be so stupid.")
            print("")
            quit()

    else:
        print("")
        print("That was not one of the options. ")
        print("")
        time.sleep(2)
